### GET request
GET http://localhost:3000/api/todos
Content-Type: application/json


### POST request
POST http://localhost:3000/api/todos
Content-Type: application/json

{
  "title": "Learn Go",
  "body": "Learning Golang"
}


### PATCH request
PATCH http://localhost:3000/api/todos/67f2c910cd9e3ddc42632dcd
Content-Type: application/json



### DELETE request
DELETE http://localhost:3000/api/todos/67f2c910cd9e3ddc42632dcd
Content-Type: application/json
